name: warehouse_project
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.3
  bitsdojo_window: ^0.1.5
  adaptive_scrollbar: ^2.1.2
  flutter_svg: ^2.0.5
  fl_chart: ^0.62.0
  image_picker: ^0.8.8
  lottie: ^2.2.0
  icons_plus: ^4.0.0
  dio: ^5.2.1+1
  http: ^1.0.0
  path: ^1.8.0
  awesome_snackbar_content: ^0.1.3
  readmore: ^2.2.0
  flutter_secure_storage: ^8.0.0
  get: ^4.6.5
  logger: ^1.4.0
  window_manager: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/