import 'package:get/get.dart';

class LanguageService extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'available in stock': 'Available in stock',
          'i have it': 'I have it',
          'product name': 'Product name',
          'quantity': 'Quantity',
          'the date': 'The date',
          'next': 'Next',
          'previous': 'Previous',
          'create product': 'Create product',
          'transaction': 'Transaction',
          'home page': 'Home page',
          'search': 'Search',
          'send': 'Send',
          'close': 'Close',
          'product quantity': 'Product quantity',
          'about the product': 'About the product',
          'price': 'Price',
          'user search': 'User search',
          'product search': 'Product search',
          'refusal': 'Refusal',
          'acceptance': 'Acceptance',
          'settings': 'Settings',
          'first name': 'First name',
          'last name': 'Last name',
          'password': 'Password',
          'again password': 'Again password',
          'do you have an account ?': 'Do you have an account ?',
          'don\'t have an accaunt ?': 'Don\'t have an accaunt ?',
          'sign in': 'Sign In',
          'sign up': 'Sign Up',
          'chat': 'Chat',
          'kg': 'Kg',
          'piece': 'Piece',
          'liter': 'Liter',
          'email': 'Email',
          'my account': 'My Account',
          'city:': 'City:',
          'phone:': "Phone:",
          'receiver': 'Receiver',
          'sender': 'Sender',
          'show more': 'Show more',
          'show less': 'Show less',
          'transfers': 'Transfers',
          'log out': 'Log out',
          'transaction history': 'Transaction History'
        },
        'uz_UZ': {
          'available in stock': 'Omborda mavjud',
          'i have it': 'Menda mavjud',
          'product name': 'Mahsulot nomi',
          'quantity': 'Miqdori',
          'the date': 'Sana',
          'next': 'Keyingisi',
          'previous': 'Oldingi',
          'create product': 'Mahsulot yaratish',
          'transaction': 'Tranzaksiya',
          'home page': 'Bosh sahifa',
          'search': 'Qidiruv',
          'send': 'Yuborish',
          'close': 'Yopish',
          'product quantity': 'Mahsulot miqdori',
          'about the product': 'Mahsulot haqida',
          'price': 'Narxi',
          'user search': 'Foydalanuvchi qidiruvi',
          'product search': 'Mahsulot qidirish',
          'refusal': 'Rad etish',
          'acceptance': 'Qabul qilish',
          'settings': 'Sozlamalar',
          'first name': 'Ism',
          'last name': 'Familiya',
          'password': 'Parol',
          'again password': 'Yana parol',
          'do you have an account ?': 'Hisobingiz bormi ?',
          'don\'t have an accaunt ?': 'Hisobingiz yo\'qmi ?',
          'sign in': 'Tizimga kirish',
          'sing up': 'Ro\'yxatdan o\'tish',
          'chat': 'Chat',
          'kg': 'Kg',
          'piece': 'Dona',
          'liter': 'Liter',
          'email': 'Elektron pochta',
          'my account': 'Mening hisobim',
          'city:': 'Shahar:',
          'phone': 'Telefon:',
          'receiver': 'Qabul qiluvchi',
          'sender': 'Yuboruvchi',
          'show less': 'Kamroq ko\'rsatish',
          'show more': 'Ko\'proq ko\'rsatish',
          'transfers': 'O\'tkazmalar',
          'log out': 'Chiqish',
          'transaction history': 'Tranzaktsiyalar tarixi'
        },
        'ru_RU': {
          'available in stock': 'Доступно на складе',
          'i have it': 'у меня есть это',
          'product name': 'Наименование товара',
          'quantity': 'Количество',
          'the date': 'Дата',
          'next': 'Следующий',
          'previous': 'Предыдущий',
          'create product': 'Создать продукт',
          'transaction': 'Сделка',
          'home page': 'Домашняя страница',
          'search': 'Поиск',
          'send': 'Отправлять',
          'close': 'Закрывать',
          'product quantity': 'Количество продукта',
          'about the product': 'О продукте',
          'price': 'Цена',
          'user search': 'Поиск пользователя',
          'product search': 'Поиск продукта',
          'refusal': 'Отказ',
          'acceptance': 'Принятие',
          'settings': 'Настройки',
          'first name': 'Имя',
          'last name': 'Фамилия',
          'password': 'Пароль',
          'again password': 'Снова пароль',
          'do you have an account ?': 'У тебя есть аккаунт ?',
          'don\'t have an accaunt ?': 'Нет аккаунта ?',
          'sign in': 'Войти',
          'sign up': 'Зарегистрироваться',
          'chat': 'Чат',
          'kg': 'Кг',
          'piece': 'Кусок',
          'liter': 'Литр',
          'email:': 'Электронная почта',
          'my account': 'Мой счет',
          'city:': 'Город:',
          'phone:': 'Телефон:',
          'receiver': 'Получатель',
          'sender': 'Отправитель',
          'show less': 'Показывай меньше',
          'show more': 'Показать больше',
          'transfers': 'Трансферы',
          'log out': 'Выйти',
          'transaction history': 'История транзакций',
        },
      };
}
